server:
  port: 8888

#management:
#  context-path: /admin

endpoints:
  shutdown:
    enabled: true
  restart:
    enabled: true
  health:
    sensitive: false

spring:
  # declare the default Spring profile, which can be overridden at the command=line, eg java -jar -Dspring.profiles.active=production foo.war
#  profiles:
#    activ: default
#  rabbitmq:
#    addresses: localhost:5672
#    host: 192.168.44.130
#    port: 5672
#    virtualHost: /
#    username: guest
#    password: guest
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/spring-cloud-samples/config-repo
          uri: https://github.com/IgorShare/spring-cloud-config-demo
#          uri: https://github.com/mstine/config-repo
#security:
#  user:
#    name: user
#    password: secret

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
