info:
  component: Consumer

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

#hystrix:
#  stream:
#    bus:
#      enabled: true
#      sendRate: 600

#turbine:
#  appConfig: mysvc
##  aggregator:
##    clusterConfig: CONSUMER
#  clusterNameExpression: new String("default")

server:
  port: 8080

# Separates management port from the main one
#management:
#  port: 8990

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    registryFetchIntervalSeconds: 5
##    serviceUrl:
##      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:password@localhost:8761}/eureka/


#producer:
#  ribbon:
#    ServerListRefreshInterval: 5000

# disable Ribbon's cicruit breaker and rely soley on Hystrix.
# this helps to avoid confusion.
# see https://github.com/Netflix/ribbon/issues/15
#niws:
#  loadbalancer:
#    availabilityFilteringRule:
#      filterCircuitTripped: false
