#!/bin/bash
#./gradlew build
java -jar build/libs/mysvc-0.1.0.jar
# java -jar build/libs/mysvc-0.1.0.jar --greeting="whoot" --server.port=9000 --spring.config.name=production
# java -jar build/libs/mysvc-0.1.0.jar --spring.profiles.active=spanish

# https://spring.io/blog/2015/01/20/microservice-registration-and-discovery-with-spring-cloud-and-netflix-s-eureka
# monitor registry: http://localhost:8761

# spring.config.name - default application, can be comma-separated list
# spring.config.location - a Resource path, overrides name

# Explanation of the dashboard: https://github.com/Netflix/Hystrix/wiki/Dashboard#installation-of-dashboard
# Video of a running dashboard: http://techblog.netflix.com/2012/12/hystrix-dashboard-and-turbine.html
