#!/bin/bash
./gradlew build
GREETING="Yo" java -jar build/libs/mysvc-0.1.0.jar
# java -jar build/libs/mysvc-0.1.0.jar --greeting="whoot" --server.port=9000 --spring.config.name=production
# java -jar build/libs/mysvc-0.1.0.jar --spring.profiles.active=spanish
# curl -X POST http://localhost:8888/bus/refresh

# spring.config.name - default application, can be comma-separated list
# spring.config.location - a Resource path, overrides name
