server:
  port: ${PORT:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  dashboard:
    path: /dashboard
  server:
    waitTimeInMsWhenSyncEmpty: 1
#  password: ${SECURITY_USER_PASSWORD:password}
