info:
  component: Producer

spring:
  application:
    name: producer

server:
  port: ${PORT:8080}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
