#!/bin/bash
#./gradlew build
java -jar build/libs/eureka-0.1.0.jar

# https://spring.io/blog/2015/01/20/microservice-registration-and-discovery-with-spring-cloud-and-netflix-s-eureka
# monitor registry: http://localhost:8761

# http://localhost:8761/dashboard
# /	Home page (HTML UI) listing service registrations
# /eureka/apps	Raw registration metadata
